### PR TITLE
Updated namespace (psr-0 to psr-4)

### PR DESCRIPTION
**Pull request by tricksunga**

### CODE REVIEW

**Comment by mikecarroll** [comment]
Thanks! My PHP skills aren't very strong, would this mean we also need to change the require statement for composer.json in the docs? Right now it is:

```
{
    "require": {
        "aquaio/aqua-io": "*"
    }
}
```

**Comment by tricksunga** [comment]
Hi Michael, no need for that, because the vendor of the package will still be aquaio as stated in the package's `composer.json` file as so:

```
{
    "name": "aquaio/aqua-io",
}
```

**Comment by tricksunga** [comment]
I also missed this part on the README file

> This package follows the `PSR-0` convention names for its classes, which means you can easily integrate these classes loading in your own autoloader.

I'll push another update to change `PSR-0` to `PSR-4`.

**Comment by mikecarroll** [comment]
:+1:

**Pull request merged**
